language: c
sudo: required

services:
        -docker

matrix:
  include:
    - env: TYPE=ubuntu
    - env: TYPE=alpine
install:
  - docker build
      -t ocaml-libmpdclient/${TYPE}
      -f .travis/Dockerfile-${TYPE}
      .

script:
  - docker run
      --interactive
      --tty
      ocaml-libmpdclient/${TYPE}
