language: c
sudo: required

services:
        -docker

matrix:
  include:
    - env: TYPE=ubuntu-17.10

install:
  - docker build
      -t ocaml-libmpdclient/${TYPE}
      -f travis/Dockerfile
      .

script:
  - docker run
      --interactive
      --tty
      ocaml-libmpdclient/${TYPE}
