version: 2
jobs:
  build:
    docker:
      - image: ocaml/opam:ubuntu-16.04_ocaml-4.06.0
        environment:
          TERM: xterm
    steps:
      - checkout
      - run:
          name: Install Ubuntu packages
          command: sudo apt update && sudo apt install -y sudo git darcs mercurial gcc g++ make wget mpd libmpd-dev aspcud m4 unzip pkg-config patch
      - run:
          name: Install OCaml environment.
          command: sudo wget https://raw.github.com/ocaml/opam/master/shell/opam_installer.sh -O - | sudo sh -s /usr/local/bin
                   && /usr/local/bin/opam init --comp 4.07.0
                   && eval `opam config env`
                   && /usr/local/bin/opam update -y
                   && /usr/local/bin/opam upgrade -y
                   && /usr/local/bin/opam install -y lwt cmdliner jbuilder odoc ounit bisect_ppx dune
      - run:
          name: Create user to run mpd
          command: sudo addgroup -S ocaml-libmpdclient
                   && sudo adduser -S -G ocaml-libmpdclient ocaml-libmpdclient
                   && echo "ocaml-libmpdclient ALL=(ALL:ALL) NOPASSWD:ALL"
                   | sudo EDITOR=tee visudo -f /etc/sudoers.d/ocaml-libmpdclient
      - run:
          name: Prepare the mpd data for tests.
          command: mkdir -p /tmp/mpd/music
                  && mkdir /tmp/mpd/playlists
                  && cp .travis/*.mp3 /tmp/mpd/music/
                  && ls -1 /tmp/mpd/music/ > /tmp/mpd/playlists/bach.m3u
                  && echo "/tmp/mpd/music/kunst01.mp3" > /tmp/mpd/playlists/bach1.m3u
                  && sudo chown -R ocaml-libmpdclient:ocaml-libmpdclient /tmp/mpd
      - run:
          name: Run Mpd server in background.
          command: sudo mpd .travis/mpd.conf
                   && cat /tmp/mpd/mpd.log
                   && cat /tmp/mpd.error
          background: true
      - run:
          name: Run the tests
          command: eval `opam config env` && make test
