FROM ocaml/opam2:ubuntu-lts

RUN \
  sudo apt update && \
  sudo apt install -y \
    sudo \
    git \
    darcs \
    mercurial \
    gcc \
    g++ \
    make \
    wget \
    mpd \
    libmpd-dev \
    aspcud \
    m4 \
    unzip \
    pkg-config \
    patch

RUN \
  sudo useradd --user-group --create-home ocaml-libmpdclient

RUN \
  echo "ocaml-libmpdclient ALL=(ALL:ALL) NOPASSWD:ALL" | \
    sudo EDITOR=tee visudo -f /etc/sudoers.d/ocaml-libmpdclient

USER ocaml-libmpdclient
ENV WDIR=/home/ocaml-libmpdclient/ocaml-libmpdclient
ENV TMP=/tmp
ENV U=ocaml-libmpdclient
ENV HOME=/home/ocaml-libmpdclient
COPY . /home/ocaml-libmpdclient/ocaml-libmpdclient
RUN sudo chown -R $U:$U $WDIR
WORKDIR /home/ocaml-libmpdclient/ocaml-libmpdclient
RUN opam init --disable-sandboxing \
  && opam install lwt cmdliner jbuilder odoc ounit bisect_ppx dune logs fmt
