version: '3.7'
services:
  mpd:
    build:
      context: ../
      dockerfile: .travis/Dockerfile-mpd
    ports:
      - 6600:6600
  ubuntu:
    build:
      context: ../
      dockerfile: .travis/Dockerfile-ubuntu
    depends_on:
      - mpd
