FROM ocaml/opam2:alpine-3.9

RUN \
  sudo addgroup -S ocaml-libmpdclient && sudo adduser -S -G ocaml-libmpdclient ocaml-libmpdclient

RUN sudo apk update && sudo apk add git m4 mpd mpc ncmpc

RUN \
  echo "ocaml-libmpdclient ALL=(ALL:ALL) NOPASSWD:ALL" | \
    sudo EDITOR=tee visudo -f /etc/sudoers.d/ocaml-libmpdclient

USER ocaml-libmpdclient

COPY . /home/ocaml-libmpdclient/ocaml-libmpdclient
ENV WDIR=/home/ocaml-libmpdclient/ocaml-libmpdclient
ENV TMP=/tmp
ENV U=ocaml-libmpdclient
ENV HOME=/home/ocaml-libmpdclient
COPY . /home/ocaml-libmpdclient/ocaml-libmpdclient
RUN sudo chown -R $U:$U $WDIR
WORKDIR /home/ocaml-libmpdclient/ocaml-libmpdclient
RUN opam init  --disable-sandboxing \
  && opam install lwt cmdliner jbuilder dune odoc ounit bisect_ppx logs fmt

