FROM ubuntu:17.04

RUN \
  apt update && \
  apt install -y \
    sudo \
    git \
    darcs \
    mercurial \
    gcc \
    g++ \
    make \
    wget \
    mpd \
    libmpd-dev \
    aspcud \
    m4 \
    unzip \
    pkg-config

RUN \
  useradd --user-group --create-home ocaml-libmpdclient

RUN \
  echo "ocaml-libmpdclient ALL=(ALL:ALL) NOPASSWD:ALL" | \
    EDITOR=tee visudo -f /etc/sudoers.d/ocaml-libmpdclient

USER ocaml-libmpdclient

COPY . /home/ocaml-libmpdclient/ocaml-libmpdclient
RUN sudo chown -R ocaml-libmpdclient:ocaml-libmpdclient /home/ocaml-libmpdclient/ocaml-libmpdclient
RUN sudo cp /home/ocaml-libmpdclient/ocaml-libmpdclient/travis/mpd.conf /etc/mpd.conf
RUN sudo chmod 644 /etc/mpd.conf
RUN mkdir /home/ocaml-libmpdclient/mpd
RUN mkdir /home/ocaml-libmpdclient/mpd/music
RUN mkdir /home/ocaml-libmpdclient/mpd/playlists
RUN wget -P /home/ocaml-libmpdclient/mpd/music -i /home/ocaml-libmpdclient/ocaml-libmpdclient/free_mp3_urls.txt
RUN ls -1 /home/ocaml-libmpdclient/mpd/music/ > /home/ocaml-libmpdclient/mpd/playlists/bach.m3u
RUN echo "/home/ocaml-libmpdclient/mpd/music/kunst01.mp3" > /home/ocaml-libmpdclient/mpd/playlists/bach1.m3u
WORKDIR /home/ocaml-libmpdclient/ocaml-libmpdclient
RUN wget https://raw.github.com/ocaml/opam/master/shell/opam_installer.sh -O - | sudo sh -s /usr/local/bin
RUN /usr/local/bin/opam init --comp 4.05.0
RUN opam install lwt cmdliner jbuilder odoc ounit
RUN echo ". /home/ocaml-libmpdclient/.opam/opam-init/init.sh > /dev/null 2> /dev/null || true" > /home/ocaml-libmpdclient/ocaml-libmpdclient/runtest.sh
RUN echo "mpd" >> /home/ocaml-libmpdclient/ocaml-libmpdclient/runtest.sh
RUN echo "jbuilder build @runtravistest" >> /home/ocaml-libmpdclient/ocaml-libmpdclient/runtest.sh
CMD bash -ex /home/ocaml-libmpdclient/ocaml-libmpdclient/runtest.sh
